### ISSUE TITLE
As a library owner, I want to add library information so that it add to system after admin accept it.

### ISSUE THREAD

**Issue by ahamddrabkah** [amer-sabah/bookshelf#16]
Required tables :
library(id , library_name, location,  image, owner_id)
owner(id , username, password)

**Comment by ahamddrabkah** [comment]
@MohammadNidal99  please test add library operation

**Comment by MohammadNidal99** [comment]
@ahamddrabkah user can add a library with empty fields please, add constraints on all fields.

**Comment by ahamddrabkah** [comment]
@MohammadNidal99  I fixed it , please test it again and inform me with updates

**Comment by amer-sabah** [comment]
@Amalqazaq please test
