### ISSUE TITLE
Database schema & data scripts

### ISSUE THREAD

**Issue by AsemLab** [amer-sabah/bookshelf#37]
[Schema EDITED.txt](https://github.com/amer-sabah/bookshelf/files/7147468/Schema.EDITED.txt)

**Comment by AsemLab** [comment]
[books.txt](https://github.com/amer-sabah/bookshelf/files/7147472/books.txt)

**Comment by maiqamaj** [comment]
[customer.txt](https://github.com/amer-sabah/bookshelf/files/7147896/customer.txt)

**Comment by maiqamaj** [comment]
[buy_operations.txt](https://github.com/amer-sabah/bookshelf/files/7147949/buy_operations.txt)

**Comment by Amalqazaq** [comment]
[borrow_operations.txt](https://github.com/amer-sabah/bookshelf/files/7148619/borrow_operations.txt)

**Comment by ahamddrabkah** [comment]
Final update on schema (add id to books_in_library) and all data 

[Schema_final.txt](https://github.com/amer-sabah/bookshelf/files/7148628/Schema_final.txt)
[data.txt](https://github.com/amer-sabah/bookshelf/files/7148629/data.txt)

**Comment by AsemLab** [comment]
###UPDATE
Add **AUTO_INCREAMENT** to all primary keys and update the data script according to this edit.

[Schema_final.txt](https://github.com/amer-sabah/bookshelf/files/7149589/Schema_final.txt)

[data.txt](https://github.com/amer-sabah/bookshelf/files/7149590/data.txt)

**Comment by maiqamaj** [comment]
UPDATE
Add new table booksbag 

[Schema_final.txt](https://github.com/amer-sabah/bookshelf/files/7149742/Schema_final.txt)
[data.txt](https://github.com/amer-sabah/bookshelf/files/7149743/data.txt)

**Comment by Leenaiman98** [comment]
[data.txt](https://github.com/amer-sabah/bookshelf/files/7150007/data.txt)

**Comment by ahamddrabkah** [comment]
Last update of the schema 
[Schema_last_update.txt](https://github.com/amer-sabah/bookshelf/files/7153007/Schema_last_update.txt)

**Comment by AsemLab** [comment]
**There is no change on my data:**

[Books_data.txt](https://github.com/amer-sabah/bookshelf/files/7153936/Books_data.txt)

**Comment by AsemLab** [comment]
### Books & categories tables data

[books_&_categories.txt](https://github.com/amer-sabah/bookshelf/files/7154544/books_._categories.txt)

**Comment by ahamddrabkah** [comment]
Last update for schema (add id column to permission table) and last update for data (add books and categories) 
[Schema_last_update.txt](https://github.com/amer-sabah/bookshelf/files/7156720/Schema_last_update.txt)
[data_last_update.txt](https://github.com/amer-sabah/bookshelf/files/7156722/data_last_update.txt)

**Comment by Amalqazaq** [comment]
last update on data (add books_in_library and borrow_op
[data_last_update.txt](https://github.com/amer-sabah/bookshelf/files/7158242/data_last_update.txt)
erations )

**Comment by Leenaiman98** [comment]
[data_last_last_updated.txt](https://github.com/amer-sabah/bookshelf/files/7163371/data_last_last_updated.txt)

**Comment by ahamddrabkah** [comment]
Last update for schema (add status column to libraries table) and last update for data (books_ratings and libraries_ratings
[data_last_updated.txt](https://github.com/amer-sabah/bookshelf/files/7163796/data_last_updated.txt)
[Schema_last_update.txt](https://github.com/amer-sabah/bookshelf/files/7163797/Schema_last_update.txt)
 )

**Comment by maiqamaj** [comment]
[buy_operations.txt](https://github.com/amer-sabah/bookshelf/files/7163800/buy_operations.txt)

last update on data (add to buy_operations)

**Comment by maiqamaj** [comment]
[data_last_updated.txt](https://github.com/amer-sabah/bookshelf/files/7164954/data_last_updated.txt)

[Schema_last_update (1).txt](https://github.com/amer-sabah/bookshelf/files/7164959/Schema_last_update.1.txt)

Last update for schema (change column in buy_operations) and last update for data (buy_operations)

**Comment by ahamddrabkah** [comment]
Last update for schema (borrow_operations table as BorrowOperation entity) and last update for data (borrow_operations 

[Schema_last_update.1.txt](https://github.com/amer-sabah/bookshelf/files/7188656/Schema_last_update.1.txt)
[data_last_updated.txt](https://github.com/amer-sabah/bookshelf/files/7188657/data_last_updated.txt)
)

**Comment by AsemLab** [comment]
### Update the borrow operations data

[data_last_updated.txt](https://github.com/amer-sabah/bookshelf/files/7191649/data_last_updated.txt)

**Comment by Amalqazaq** [comment]
**Last update on schema (add status column in borrow_operations) and update data for week 1 (not include update from @AsemLab ) **
[new_data.txt](https://github.com/amer-sabah/bookshelf/files/7192960/new_data.txt
[Schema_last_update.1.txt](https://github.com/amer-sabah/bookshelf/files/7192961/Schema_last_update.1.txt)
)

**Comment by AsemLab** [comment]
### Update the data accorrding to @Amalqazaq modifications

[data_last_updated.txt](https://github.com/amer-sabah/bookshelf/files/7194213/data_last_updated.txt)
